### ISSUE TITLE
ログインメール通知が大量にくる

### ISSUE THREAD

**Issue by hayashi-ay** [AkkyOrz/review-slot-watcher-42#3]
監視ツールを動かすごとにログイン通知のメールが来てしまうのですが回避策とかってあったりしますかね

↓こんな感じです。
<img width="1113" alt="スクリーンショット 2022-06-23 15 57 51" src="https://user-images.githubusercontent.com/39038230/175235366-b1411280-bdc5-4090-a630-4947e4dedd62.png">

**Comment by AkkyOrz** [comment]
@hayashi-ay 
#6 で対応しました
